# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-09 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('SS', 'Sent To Sales'), ('OA', 'Offer Accepted')], default='SS', max_length=2),
        ),
        migrations.AddField(
            model_name='raterequest',
            name='status',
            field=models.CharField(choices=[('SO', 'Sent To Operations'), ('QR', 'Quotation Received'), ('OS', 'Offer Sent'), ('OA', 'Offer Accepted')], default='SO', max_length=2),
        ),
    ]
