# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-09 13:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20161009_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_freight_kg', models.CharField(blank=True, max_length=200, null=True)),
                ('fuel_sur_charge_kg', models.CharField(blank=True, max_length=200, null=True)),
                ('security_fees_kg', models.CharField(blank=True, max_length=200, null=True)),
                ('exw_charges', models.CharField(blank=True, max_length=200, null=True)),
                ('screening_fees', models.CharField(blank=True, max_length=200, null=True)),
                ('storage', models.CharField(blank=True, max_length=200, null=True)),
                ('inland', models.CharField(blank=True, max_length=200, null=True)),
                ('packing', models.CharField(blank=True, max_length=200, null=True)),
                ('taxes_duties', models.CharField(blank=True, max_length=200, null=True)),
                ('handling_fees', models.CharField(blank=True, max_length=200, null=True)),
                ('official_receipts', models.CharField(blank=True, max_length=200, null=True)),
                ('p_share', models.CharField(blank=True, max_length=200, null=True)),
                ('other_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('offer_validity', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=b'EBF284', max_length=6)),
                ('type', models.CharField(choices=[('A', 'AIR'), ('S', 'SEA')], max_length=1)),
                ('air_quotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='main.AirQuotation')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.Client')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.CreateModel(
            name='SeaQuotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_line', models.CharField(blank=True, max_length=200, null=True)),
                ('ocean_freight', models.CharField(blank=True, max_length=200, null=True)),
                ('thc', models.CharField(blank=True, max_length=200, null=True)),
                ('transporation', models.CharField(blank=True, max_length=200, null=True)),
                ('transfer', models.CharField(blank=True, max_length=200, null=True)),
                ('clearance', models.CharField(blank=True, max_length=200, null=True)),
                ('bl_fees', models.CharField(blank=True, max_length=200, null=True)),
                ('telex_release', models.CharField(blank=True, max_length=200, null=True)),
                ('free_time_at_destination', models.CharField(blank=True, max_length=200, null=True)),
                ('vessels', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_credit', models.CharField(blank=True, max_length=200, null=True)),
                ('official_receipts', models.CharField(blank=True, max_length=200, null=True)),
                ('other_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('offer_validity', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='sea_quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='main.SeaQuotation'),
        ),
    ]
