# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-09 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161009_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 9, 13, 39, 13, 703144, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('S', 'Sent To Client'), ('A', 'Accepted')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='offer',
            name='reference',
            field=models.CharField(default=b'52DAFD', max_length=6),
        ),
    ]
