# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-08 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20161208_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='reference',
            field=models.CharField(default=b'7A7341', max_length=6),
        ),
    ]
