# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-28 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161228_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='reference',
            field=models.CharField(default=b'33601C', max_length=6),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('S', 'Sent To Client'), ('A', 'Accepted'), ('D', 'Done')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('SS', 'Sent To Sales'), ('OA', 'Offer Accepted'), ('DO', 'Done')], default='SS', max_length=2),
        ),
        migrations.AlterField(
            model_name='raterequest',
            name='status',
            field=models.CharField(choices=[('SO', 'Sent To Operations'), ('QR', 'Quotation Received'), ('OS', 'Offer Sent'), ('OA', 'Offer Accepted'), ('DO', 'Done')], default='SO', max_length=2),
        ),
    ]
