# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-28 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_auto_20161228_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sales_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='reference',
            field=models.CharField(default=b'7733AD', max_length=6),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='operations_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations_operations', to=settings.AUTH_USER_MODEL),
        ),
    ]
