# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-31 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170131_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='main.Quotation'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='reference',
            field=models.CharField(default=b'694532', max_length=6),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='rate_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='main.RateRequest'),
        ),
    ]
